### PR TITLE
Make JSON files more readable

### PR DESCRIPTION
**Pull request by monzo94**
Make JSON files more readable by making the args dictionaries, using the names of the parameters as keys. This also simplifies the registry's logic a bit.

### CODE REVIEW

**Comment by Elkasitu** [comment]
I think this at least requires some discussion, this adds a lot of boilerplate don't you think?

In fact, I already think that as it is it has way too much boilerplate and I think I have a better solution for this: 

Conver to CSV, if we use CSV we only have to add a header defining each column/key, they're easy to CRUD and they can be imported into a user's spreadsheet editor of choice if they want a GUI or just manually edit the file

**Comment by monzo94** [comment]
I do agree that it is quite verbose, but it still makes it much more readable, especially when the files start getting a lot bigger.

While CSV could be another solution, I think it works better for other types of data that are more tabular than ours, like lists of numbers. With our kind of data it might be harder to parse, plus less readable because we'd have to align the columns somehow and I'm not sure if CSV handles tabs too well. So it'd only look ok-ish in GUI programs like excel, which kinda is how most people use CSV files anyway.

**Comment by monzo94** [comment]
Looking for other non-JSON solutions I found some guy who made his own parser to store data in a tabular way with the alignment I was talking about, see [here](https://i.imgur.com/byExWWn.png). But that's probably too much unnecessary work.

Also checked cataclysm dda, they do it the verbose way: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/monsters.json

**Comment by Elkasitu** [comment]
An example csv monster definition:

```csv
id,name,char,color,behavior
1,Poopy,p,"0,0,0",NullBehavior
```

We cannot align **CSV** because whitespace is taken into account for every column, it is much more compact, sure it's less readable *if* one were to open it manually, however if opened with a spreadsheet application it is very easy to add/modify/delete rows, and it's not subject to *subtle* syntax like JSON is.

First of all, I don't really think that readability of the raw file on any text editor is such an issue if there are FOSS solutions that can open and modify the file easily (LibreOffice for example).

Secondly, I don't think it's harder to parse, with the `csv` python module one can parse a csv file and it is possible to directly generate an OrderedDict where the keys are the column names defined in the first row and the values are the entries in all of the other rows [1].

Finally, the CSV format is much more flexible than JSON because we can define a lot of the syntax instead of being tied down to JSON's syntax.

> Also checked cataclysm dda, they do it the verbose way

Can we be sure that the verbosity is not tool-generated though? That's another option, creating a tool (GUI) that asks you for the attributes of the entity to create and then appends it to the file, but IMO that's the same as using the Spreadsheet editor approach except it's more work.

[1] [DictReader](https://docs.python.org/3/library/csv.html?highlight=csv#csv.DictReader)

**Comment by monzo94** [comment]
If you want to use a spreadsheet app to edit the files then fine, I was just trying to  avoid having to use any external apps for editing the data. If we're gonna use libreoffice calc / excel then csv works just fine, I'll work into it.

**Comment by monzo94** [comment]
Closed in favor of #53

**Pull request closed without merging**
